### ISSUE TITLE
Cant build from source

### ISSUE THREAD

**Issue by danhans42** [MittisBootloop/esp32_nesemu_wemosmini#1]
Hi great project - came across you on hackaday.io

I have made my own handheld device and wanted to try your code on it, but cannot build the source as its giving me the following error(s)

esp/esp32-nesemu-gpio/components/menu/charData.c:2:22: fatal error: charData.h: No such file or directory

it doesnt appear to be on the system when I pulled it from git or on here, or am I doing something really stupid?

Thanks

**Comment by MittisBootloop** [comment]
Sorry, you only need top delete this -> #include "charData.h" in the charData.c file(2. line). Should work then. I've forgotten to delete it, because my Compiler gives me no error with this line. :D
Of course I'll change this in the next few days.

**Comment by danhans42** [comment]
Thank you, will try that later. I have updated the toolchain to the latest, so maybe that is why I am seeing it and you are not.

I wanted to look at your code for your GPIO buttons and see if I could get that running on the gameboy or SMS emulator.

Thanks for the reply and great work!

:)

**Comment by MittisBootloop** [comment]
I've changed the charData file. now it should work without any changey after downloading.

That sounds great, i hope you'll upload it to github, if you get it to work.
Good luck... :+1:

**Comment by danhans42** [comment]
Perfect thank you.

Yes there are two emulators I wanted to get working. Both the gameboy and sega master system. Ill check over your modifications to psxcontroller.c for the GPIO pad routines and see if i can get it working with those. 

Thanks for all your help, and of course when done I will get them up on github.

Thanks

**Comment by danhans42** [comment]
I now have the SMS Emulator working with GPIO buttons perfectly. I will get it on github soon as I work out how to use it correctly.

My next step is to replace the directional pad with the analogue joystick from a PSP2000, so I can make an even more compact machine. Rather than using the WROOM, I am using the TTGO T8 which is Wrover based, so I can look at porting over some games from the odroid g. This also has the added benefit of MicroSD so I can try and expand the machine and my programming knowledge even further.

Thanks for the project, it certainly inspired me to push on with a dead project of mine.

Thanks again,

**Comment by MittisBootloop** [comment]
Great to hear this. I'm glad that this helped you to revive a dead project. The idea with the joystick sounds pretty nice...I wish you much fun building it!

**Comment by pooobum** [comment]
Does it work well or not brykerr78@
