### ISSUE TITLE
Change screen pin, run failed

### ISSUE THREAD

**Issue by LilyGO** [MittisBootloop/esp32_nesemu_wemosmini#4]
Hi
My board has the remaining extension modules, so I used other pins. I first modified it in menuconfig, and then changed the macro definition of spi_lcd.c. However, the screen does not display the image properly.
What is the reason for not changing the screen pin? Is there any solution?

Best blessing

**Comment by MittisBootloop** [comment]
Did you also change the Pins in menu.c?
I have to quote lemmingDev here, "...the code is in a bit of a mess...". 😅
I hope this might help.

**Comment by badvision** [comment]
Also in the menu code, you need to switch it to VSPI instead of HSPI.  If you do that you can go to 80mhz bus and that improves the speed somewhat.
